### ISSUE TITLE
getByIds and getByIdsUsingJoiningTable functions do not accept 7 arguments

### ISSUE THREAD

**Issue by mohib0306** [gajus/postloader#5]
The `NotFoundError` argument that is passed from the https://github.com/gajus/postloader/blob/54a6f4284cd648a4f8dd9af85af6aa2718a5afd3/src/utilities/generateDataLoaderFactory.js#L30 and https://github.com/gajus/postloader/blob/54a6f4284cd648a4f8dd9af85af6aa2718a5afd3/src/utilities/generateDataLoaderFactory.js#L43 are not longer supported, since the routines (`getByIds` and `getByIdsUsingJoiningTable`) only accepts  6 arguments rather than 7.

**Comment by gajus** [comment]
You can import the `NotFoundError` from `postloader` and use to catch the error, e.g.

```js
import {
  NotFoundError
} from 'postloader';

// ..

try {
  await MovieByIdLoader.load(1);
} catch (error) {
  if (error instanceof NotFoundError) {
     // ..
  }
}

```

**Comment by mohib0306** [comment]
The problem is not in the example but rather in the generated loaders by `postloader/src/utilities/generateDataLoaderFactory.js`.  As you can see that it returns a loader along with 7 arguments which is not correct and should return a `getByIds` function with 6 parameters

**Comment by gajus** [comment]
Fixed.

**Comment by mohib0306** [comment]
Thanks 👍
